# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad <- function(x, A, mu_u, mu_s, mu_v, noiseType, noiseParams, trans_u, n_randomSample) {
    .Call(`_cycvb_grad`, x, A, mu_u, mu_s, mu_v, noiseType, noiseParams, trans_u, n_randomSample)
}

