# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' grad
#'
#' @param x The observed data following a structural equation model
#' @param A Parameter a of the hard concrete distribution
#' @param mu_u U matrix of the SVD of matrix mu
#' @param mu_s Diagnal matrix of the SVD of matrix mu
#' @param mu_v V matrix of the SVD of matrix mu
#' @param noiseType Type of the distribution of the noise in the structural equation model. It needs to be one of the following: 'gaussian','t','laplace','gumbel'.
#' @param noiseParams Parameter of noise distribution
#' @param trans_u Monte Carlo sample of a transformation of uniform distribution
#' @param n_randomSample Monte Carlo sample of normal distribution
#'
#' @return gradient of ELBO funcion
grad <- function(x, A, mu_u, mu_s, mu_v, noiseType, noiseParams, trans_u, n_randomSample) {
    .Call(`_cycvb_grad`, x, A, mu_u, mu_s, mu_v, noiseType, noiseParams, trans_u, n_randomSample)
}

